[package]
name = "enigma-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
colog = "1.3.0"
dotenv = "0.15.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"]}
tokio = { version = "1.44.2", features = ["full"] }
tokio-postgres = "0.7.13"
toml = "0.8.20"
