services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: enigma
      POSTGRES_DB: enigma
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U enigma']
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 2s

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.4-alpine
    ports:
      - "5672:5672"
    restart: unless-stopped
    env_file:
      - ".env"
    volumes:
      - rmqdata:/var/lib/rabbitmq

volumes:
  pgdata:
  rmqdata: